#!/bin/bash
cd /mnt/d/Desktop/gardenia-master

echo "========================================="
echo "mem_monitor.sh 运行所需文件清单"
echo "========================================="

echo ""
echo "【1】脚本文件"
echo "-----------------------------------------"
echo "mem_monitor.sh (内存监控脚本)"

echo ""
echo "【2】可执行文件 (bin/)"
echo "-----------------------------------------"
ls -lh bin/cc_omp bin/bfs_omp_base bin/pr_omp_base 2>/dev/null

echo ""
echo "【3】数据集文件 (示例)"
echo "-----------------------------------------"
echo "需要提供一个数据集文件路径作为第一个参数"
echo "示例数据集:"
ls datasets/test_scc.mtx datasets/web-Google.el 2>/dev/null

echo ""
echo "【4】系统依赖命令"
echo "-----------------------------------------"
echo "需要以下系统命令（通常默认存在）:"
echo "  - bash (shell解释器)"
echo "  - ps (进程查看)"
echo "  - bc (计算器)"
echo "  - awk (文本处理)"
echo "  - grep (文本搜索)"
echo "  - sleep (延时)"
echo "  - date (日期时间)"
echo "  - nproc (CPU核心数)"
echo "  - free (内存信息)"

echo ""
echo "【5】最小运行环境验证"
echo "-----------------------------------------"
echo "检查各命令是否可用:"
command -v bash && echo "  ✓ bash"
command -v ps && echo "  ✓ ps"
command -v bc && echo "  ✓ bc"
command -v awk && echo "  ✓ awk"
command -v grep && echo "  ✓ grep"
command -v sleep && echo "  ✓ sleep"
command -v date && echo "  ✓ date"
command -v nproc && echo "  ✓ nproc (CPU核心数: $(nproc))"
command -v free && echo "  ✓ free (内存: $(free -m | grep Mem | awk '{print $2}') MB)"

echo ""
echo "========================================="
echo "使用示例"
echo "========================================="
echo ""
echo "# SCC算法测试:"
echo "./mem_monitor.sh datasets/test_scc.mtx scc 0.2"
echo ""
echo "# BFS算法测试:"
echo "./mem_monitor.sh datasets/test_scc.mtx bfs 0.2"
echo ""
echo "# PR算法测试:"
echo "./mem_monitor.sh datasets/test_pr.mtx pr 0.2"
echo ""
echo "# 大数据集测试:"
echo "./mem_monitor.sh datasets/web-Google.el scc 0.5"